name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          
        sm_version:
          - "1.10"
          - "1.11"
          - "latest"
          
        include:
          - sm_version: latest
            sm_branch: master
            
          - sm_version: "1.10"
            sm_branch: "1.10-dev"
            
          - sm_version: "1.11"
            sm_branch: "1.11-dev"
            
          - os: ubuntu-20.04
            os_short: linux

    steps:
      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install -y --no-install-recommends gcc-multilib g++-multilib 

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: extension
          submodules: recursive

      - name: Getting SourceMod ${{ matrix.sm_version }}
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive
      
      - name: Checkout AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild
      
      - name: Install AMBuild
        uses: BSFishy/pip-action@v1
        with:
          packages: ./ambuild

      - name: Build hiredis
        working-directory: extension/hiredis
        shell: bash
        env: 
          CFLAGS: -Werror -m32
          CXXFLAGS: -Werror -m32
        run: |
          mkdir build && cd build
          cmake .. && make
        
      - name: Build
        working-directory: extension
        shell: bash
        run: |
          mkdir build && cd build
          python ../configure.py --enable-optimize --targets=x86 --sm-path="${{ github.workspace }}/sourcemod-${{ matrix.sm_version }}"
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.sm_version }}-${{ matrix.os_short }}
          path: extension/build/package
